"""Ajout du chat

Revision ID: 627bf4588769
Revises: d4d0504d66f9
Create Date: 2025-02-13 11:45:20.031115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627bf4588769'
down_revision = 'd4d0504d66f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recette_id'], ['recette.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
