"""Ajout du champ publique aux recettes

Revision ID: d4d0504d66f9
Revises: 
Create Date: 2025-02-13 11:24:21.351204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d0504d66f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publique', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recette', schema=None) as batch_op:
        batch_op.drop_column('publique')

    # ### end Alembic commands ###
